### ISSUE TITLE
[Bug] Undo command that does not change the state results in unexpected behaviour with Redo command

### ISSUE THREAD

**Issue by chrisjohntan** [AY2425S1-CS2103T-F14a-4/tp#152]
Undo and redo commands exhibit unexpected behavior when undo does not change the state of CampusConnect.

Steps to replicate:
1. Launch CampusConnect
2. Do an action that alters the state
3. Apply one undo command, which should revert CampusConnect to the state it was launched with
4. Apply one undo command again, this visually does nothing (expected, since there is nothing to undo)
5. Apply one redo command, this visually has no effect (unexpected, the action in step 2 should have been redone)

**Comment by CYX22222003** [comment]
Could you provide a specific test case that cause the error? I try on my laptop and the issue does not appear.

**Comment by chrisjohntan** [comment]
I can no longer provide a specific test case because it works now 🗿

**Comment by CYX22222003** [comment]
Then, I think we can close the issue for now.
