### ISSUE TITLE
Add a table of expected command results to the UG

### ISSUE THREAD

**Issue by chrisjohntan** [AY2425S1-CS2103T-F14a-4/tp#235]
Should we add a section for examples of expected results of commands, i.e. what will appear in the results text box when the command either succeeds or fails

**Comment by CYX22222003** [comment]
I think we can do it by placing some screenshots under examples

**Comment by chrisjohntan** [comment]
> I think we can do it by placing some screenshots under examples

Deliverables say to avoid overusing screenshots

**Comment by KrashKart** [comment]
I think this is not necessary since UG does not need to contain too many details (as stated in the website), but if you guys think it is needed we can add some small descriptions (not necessarily screenshots)

**Comment by CYX22222003** [comment]
Shall we close the issue?
