### ISSUE TITLE
Cattag bug when we edit multiple tags

### ISSUE THREAD

**Issue by blackpanther9229** [AY2425S1-CS2103T-F14a-4/tp#252]
For example, we have tag [tag1] of cattegory general and [tag2] of cattegory acads
If we execute: "cattag t/tag1 t/tag2 acad", the app reponse: "Current category of [ho] is already ACADEMICS" 
Should this be fixed?

**Comment by yooplo** [comment]
I think it is fine as it tells the user only which tag is not suitable, unless you want to improve it by including the approved tag as well?

**Comment by blackpanther9229** [comment]
> I think it is fine as it tells the user only which tag is not suitable, unless you want to improve it by including the approved tag as well?

Yeh I think so
