### ISSUE TITLE
Cattag bug when calling the same tag multiples time in one command

### ISSUE THREAD

**Issue by blackpanther9229** [AY2425S1-CS2103T-F14a-4/tp#254]
Let the current category of tag [tag1] be general.
If we execute: "cattag t/tag1 t/tag1 acads", the app reponses: "Current category of [CS2100] is already ACADEMICS"

I haven't found the real origin of the problem, but one of the possible way to fix it is by romving the feature: Attempts to set a tag to its current category will cause the whole command to be rejected. To be specific, I deleted this line in CategorizeTagCommand#execute 
`if (isDuplicateCategory(existingCat)) {
        throw new CommandException(String.format(MESSAGE_DUPLICATE_CATEGORY, targetTag, updatedCategory));
}`
and it works.

**Comment by CYX22222003** [comment]
removing this line may cause the undo redo to behave unexpectedly. As cattag may not change the actual data but an old version of data is saved.

**Comment by CYX22222003** [comment]
a possible way of improvement is to check for duplicate tags while parsing.

**Comment by chrisjohntan** [comment]
I will fix this by referencing the addtag command.
`cattag t/X t/X C` will succeed and categorize X under C.
