### ISSUE TITLE
Add steps for manual testing to DG

### ISSUE THREAD

**Issue by chrisjohntan** [AY2425S1-CS2103T-F14a-4/tp#255]
Refer to [w08-1](https://ay2425s1-cs2103t-w08-1.github.io/tp/DeveloperGuide.html#appendix-instructions-for-manual-testing) for an example

**Comment by chrisjohntan** [comment]
Commands left to include:
- `redo`
- `addtag`
- `add` ?
- `edit` ?

**Comment by KrashKart** [comment]
I think `add` and `edit` are not required since we did not change them
