### ISSUE TITLE
[PE-D][Tester B] Ability to add numbers in the name field

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-F14a-4/tp#293]
I am able to add numbers without any characters into the name field. I acknowledge that numbers might appear in names, but I doubt that that any individual's names only contains numbers.

![image.png](https://raw.githubusercontent.com/Vatinius/ped/main/files/c0b289b0-605d-4f36-8d0b-a95df65d8d95.png)

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: Vatinius/ped#2

**Comment by CYX22222003** [comment]
Maybe we can include in documentation to justify this. When there are two contacts with same name, we allow users to use number to differentiate them.
