### ISSUE TITLE
[PE-D][Tester B] Help window should contain a quick reference for commands

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-F14a-4/tp#310]
As a user, I might want to view all commands at a glance by running the `help` command, instead of being directed to the User Guide website. 

Moreover, as a new user, if I use CampusConnect without connecting to the the internet, I will not be able to access the User Guide website entirely and may not know how to use the commands.

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: Vatinius/ped#5

**Comment by KrashKart** [comment]
Closed, might implement this as a future feature
