### ISSUE TITLE
[PE-D][Tester E] cattag command is case sensitive

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-F14a-4/tp#315]
**Description:** May cause inconvenience to users who type fast, similar to previous bug on tagadd case sensitivity, it causes minor inconvenience.

 **Steps to Reproduce:**

1. Cattag command a tag but change the capitalisation
2. E.g cattag t/CS2030-TA  acads does not work on t/cs2030-ta and vice versa

**Suggestion:** Allow case insensitive matching for tags
![cattag insensitive.png](https://raw.githubusercontent.com/jonushzw/ped/main/files/1d9f64e5-8dce-443f-affc-6a17cd63ab94.png)

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: jonushzw/ped#8

**Comment by KrashKart** [comment]
I disagree, if users can type fast they will still benefit from this system anyway. Any others have thoughts? I vote to close this issue
