### ISSUE TITLE
[PE-D][Tester A] find t/ did not give intended results

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-F14a-4/tp#319]
![Screenshot 2024-11-08 at 4.40.10 PM.png](https://raw.githubusercontent.com/ChinSekYi/ped/main/files/1a1b8079-d84e-47e4-917f-2f718bf866a5.png)

I wish to find all contacts without any tags. But `find t/` returns me all contacts. It's the same as `list`.

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: ChinSekYi/ped#9

**Comment by KrashKart** [comment]
Closed, will fix in a separate issue
