### ISSUE TITLE
[PE-D][Tester B] Unable to add chinese characters as names.

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-F14a-4/tp#341]
As a user, I might have Chinese friends who I want to save into CampusConnect using their Chinsese names. However, CampusConnect does not allow me to.

-------------
Labels: `severity.VeryLow` `type.FeatureFlaw`
original: Vatinius/ped#11

**Comment by CYX22222003** [comment]
Supporting multilanguage is not in the project scope.
