### ISSUE TITLE
[PE-D][Tester D] GUI for tags feels unintuitive

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-F14a-4/tp#350]
I might be missing some feature, but I think the GUI for the tags is just a list of all the current tags, which I'm not sure if this is necessarily a feature that such users may want? Maybe if when you find by tag it only displays the tags that the filtered list contains, it would have a clearer purpose?

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: jerrelllee/ped#6

**Comment by KrashKart** [comment]
We implemented it so users could use the tag list to understand what to `find` for, not as a supplement to the current filtered list
