### ISSUE TITLE
Categorize tags into different types

### ISSUE THREAD

**Issue by CYX22222003** [AY2425S1-CS2103T-F14a-4/tp#86]
We need minimally these categories:
1. Default (can be Unassigned)
2. Module/Course
3. CCA
4. Others

**Comment by KrashKart** [comment]
Have to rush to implement this by Thursday because v1.4 is the alpha, but no need to polish it yet

**Comment by CYX22222003** [comment]
I am not sure whether we should include this feature into our final product or not.

**Comment by chrisjohntan** [comment]
Resolved by #167
