### ISSUE TITLE
Clarifiy Find command format

### ISSUE THREAD

**Issue by chrisjohntan** [AY2425S1-CS2103T-F14a-4/tp#91]
What is the expected output of `find n/Bob p/81234567`? 
Will `p/81234567` be treated as a keyword, or will `81234567` be searched as a phone number in addition to `Bob` as a name.

**Comment by CYX22222003** [comment]
possible outcome of command in such format:
1) return all contacts that satisfy `find [key1]` and/or `find[key2`
2) throw error when multiple keys are detected

**Comment by KrashKart** [comment]
We also need to settle a similar issue, currently when we want to edit multiple tags (for example [friend] and [neighbour], we have to specify t/friend t/neighbour in separate groups, but if we wish to find by multiple tags, then we do not need separate `t/` tags: find t/friend neighbour.

Which behaviour should be use?

**Comment by KrashKart** [comment]
Issue closed, #129
